from __future__ import annotations

from typing import Any

class Config:
    def __init__(self) -> None: ...
    @staticmethod
    def from_env() -> Config: ...
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def get_all(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
