from __future__ import annotations

class ExecutionPlan:
    def children(self) -> list[ExecutionPlan]: ...
    def display(self) -> str: ...
    def display_indent(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def partition_count(self) -> int: ...
