from __future__ import annotations

from datafusion._internal.common.data_type import DataType

class DFField:
    def __init__(
        self,
        qualifier: str | None = None,
        name: str = "",
        data_type: DataType = ...,
        nullable: bool = False,
    ) -> None: ...
    def name(self) -> str: ...
    def data_type(self) -> DataType: ...
    def is_nullable(self) -> bool: ...
    def qualified_name(self) -> str: ...
    def qualifier(self) -> str | None: ...
    def strip_qualifier(self) -> DFField: ...
