from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from datafusion._internal.expr import Expr

class AggregateFunction:
    def aggregate_type(self) -> str: ...
    def is_distint(self) -> bool: ...
    def args(self) -> list[Expr]: ...
    def __repr__(self) -> str: ...
