from __future__ import annotations

from datafusion._internal.expr import Expr

class Between:
    def expr(self) -> Expr: ...
    def negated(self) -> bool: ...
    def low(self) -> Expr: ...
    def high(self) -> Expr: ...
    def __repr__(self) -> str: ...
