from __future__ import annotations

from datafusion._internal.expr import Expr

class Not:
    def expr(self) -> Expr: ...
    def __repr__(self) -> str: ...

class IsNotNull:
    def expr(self) -> Expr: ...
    def __repr__(self) -> str: ...

class IsNull:
    def expr(self) -> Expr: ...
    def __repr__(self) -> str: ...

class IsTrue:
    def expr(self) -> Expr: ...
    def __repr__(self) -> str: ...

class IsFalse:
    def expr(self) -> Expr: ...
    def __repr__(self) -> str: ...

class IsUnknown:
    def expr(self) -> Expr: ...
    def __repr__(self) -> str: ...

class IsNotTrue:
    def expr(self) -> Expr: ...
    def __repr__(self) -> str: ...

class IsNotFalse:
    def expr(self) -> Expr: ...
    def __repr__(self) -> str: ...

class IsNotUnknown:
    def expr(self) -> Expr: ...
    def __repr__(self) -> str: ...

class Negative:
    def expr(self) -> Expr: ...
    def __repr__(self) -> str: ...
