from __future__ import annotations

from datafusion._internal.expr import Expr

class Case:
    def expr(self) -> Expr: ...
    def when_then_expr(self) -> list[tuple[Expr, Expr]]: ...
    def else_expr(self) -> Expr | None: ...
    def __repr__(self) -> str: ...
