from __future__ import annotations

from datafusion._internal.common.data_type import DataType
from datafusion._internal.expr import Expr

class Cast:
    def expr(self) -> Expr: ...
    def data_type(self) -> DataType: ...
    def __repr__(self) -> str: ...

class TryCast:
    def expr(self) -> Expr: ...
    def data_type(self) -> DataType: ...
    def __repr__(self) -> str: ...
