from __future__ import annotations

from datafusion._internal.expr import Expr
from datafusion._internal.sql.logical import LogicalPlan

class Distinct:
    def input(self) -> LogicalPlan: ...
    def __repr__(self) -> str: ...
    def __name__(self) -> str: ...
