from __future__ import annotations

from datafusion._internal.common.df_schema import DFSchema
from datafusion._internal.expr import Expr
from datafusion._internal.sql.logical import LogicalPlan

class Explain:
    def explain_string(self) -> list[str]: ...
    def verbose(self) -> bool: ...
    def plan(self) -> LogicalPlan: ...
    def schema(self) -> DFSchema: ...
    def logical_optimization_succeeded(self) -> bool: ...
