from __future__ import annotations

from datafusion._internal.expr import Expr

class Like:
    def negated(self) -> bool: ...
    def expr(self) -> Expr: ...
    def pattern(self) -> Expr: ...
    def escape_char(self) -> str | None: ...
    def __repr__(self) -> str: ...

class ILike:
    def negated(self) -> bool: ...
    def expr(self) -> Expr: ...
    def pattern(self) -> Expr: ...
    def escape_char(self) -> str | None: ...
    def __repr__(self) -> str: ...

class SimilarTo:
    def negated(self) -> bool: ...
    def expr(self) -> Expr: ...
    def pattern(self) -> Expr: ...
    def escape_char(self) -> str | None: ...
    def __repr__(self) -> str: ...
