from __future__ import annotations

from datafusion._internal.common.df_schema import DFSchema
from datafusion._internal.expr import Expr
from datafusion._internal.sql.logical import LogicalPlan

class Limit:
    def skip(self) -> int: ...
    def fetch(self) -> int | None: ...
    def input(self) -> list[LogicalPlan]: ...
    def schema(self) -> DFSchema: ...
    def __repr__(self) -> str: ...
