from __future__ import annotations

from datafusion._internal.expr import Expr
from datafusion._internal.sql.logical import LogicalPlan

class Repartition:
    def input(self) -> list[LogicalPlan]: ...
    def partitioning_scheme(self) -> Partitioning: ...
    def distribute_list(self) -> list[Expr]: ...
    def distribute_columns(self) -> str: ...
    def __repr__(self) -> str: ...
    def __name__(self) -> str: ...

class Partitioning: ...
