from __future__ import annotations

from datafusion._internal.common.df_schema import DFSchema
from datafusion._internal.expr import Expr
from datafusion._internal.sql.logical import LogicalPlan

class TableScan:
    def table_name(self) -> str: ...
    def fqn(self) -> tuple[str | None, str | None, str]: ...
    def projection(self) -> list[tuple[int, str]]: ...
    def schema(self) -> DFSchema: ...
    def filters(self) -> list[Expr]: ...
    def fetch(self) -> int | None: ...
    def __repr__(self) -> str: ...
